---
# severity_overrides:
#   CUS002: ERROR
#   aws-s3-enable-versioning: HIGH
# exclude:
#   - CUS002
#   - aws-s3-enable-versioning
exclude:
  - AVD-AWS-0089
  - aws-s3-enable-bucket-logging
# checks:
#   - code: CUS001
#     description: Custom check to ensure the CostCentre tag is applied to EC2 instances
#     impact: By not having CostCentre we can't keep track of billing
#     resolution: Add the CostCentre tag
#     requiredTypes:
#     - resource
#     requiredLabels:
#     - aws_instance
#     severity: ERROR
#     matchSpec:
#       name: tags
#       action: contains
#       value: CostCentre
#     errorMessage: The required CostCentre tag was missing
#     relatedLinks:
#     - http://internal.acmecorp.com/standards/aws/tagging.html
